using UnityEngine;
using UnityEditor;
using System.IO;

/*
This script is responsible for spawning the:
1. clothed avatar model (clothed_avatar)
2. segmentation model (base_avatar_for_segmentation)
in the scene, after it has been imported and
processed by the FbxImportHandler.cs script.

It runs after the scene loads but before Start() is called on any object.
We need to run it after the scene loads because we need to find the BodyManager object in the scene.
*/
public class AvatarSpawner : MonoBehaviour
{
    // The directory that holds the clothed avatar models generated by MakeHuman and postprocessed by the FbxImportHandler.cs script.
    const string CLOTHED_AVATAR_DIRECTORY = "Assets/Base Models";

    // The script that controls the clothed avatar model.
    // We need to add this as a component to the clothed avatar model after it is spawned.
    const string AVATAR_CONTROLLER_SCRIPT = "AvatarController";

    // The name of the base avatar used for segmentation. The top-level game object that is spawned.
    const string SEGMENTATION_AVATAR_TOP_LEVEL_NAME = "base_human_avatar_for_segmentation";

    // The name of the base avatar mesh used for segmentation. A child of the base_human_avatar_for_segmentation game object that is spawned.
    const string SEGMENTATION_AVATAR_MESH_NAME = "base_avatar_for_segmentationMesh";

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] // Run after scene loads, but before Start() is called on any object.
    static void OnAfterSceneLoad()
    {
#if UNITY_EDITOR
        // Find all FBX files in the clothed avatar directory.
        Debug.Log($"[AvatarSpawner] Looking for clothed avatar models in {CLOTHED_AVATAR_DIRECTORY}");
        string [] modelGuids = AssetDatabase.FindAssets("t:Model", new [] {CLOTHED_AVATAR_DIRECTORY});

        foreach (string modelGuid in modelGuids)
        {
            string assetPath = AssetDatabase.GUIDToAssetPath(modelGuid);

            // Skip if not a .fbx file
            if (!assetPath.EndsWith(".fbx")) continue;

            Debug.Log($"[AvatarSpawner] Found clothed avatar model: {assetPath}");

            // Load the model prefab
            GameObject modelPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);

            // Skip this object if it's already in the scene.
            if (GameObject.Find(modelPrefab.name) != null) continue;

            // Spawn the model in the scene and get the Animator component
            GameObject avatarInstance = SpawnModelInScene(modelPrefab);

            // Perform setup of the model now that it is in the scene
            Animator avatarAnimator = SetupAnimatorComponent(avatarInstance, assetPath);
            AddAvatarControllerScriptToSpawnedAvatar(avatarInstance, avatarAnimator);
        }
    }

    // Spawns a model in the scene and returns the game object.
    private static GameObject SpawnModelInScene(GameObject modelPrefab)
    {
        GameObject modelInstance = Object.Instantiate(modelPrefab);
        modelInstance.name = modelPrefab.name; // removes "(Clone) from the instance's name

        // For now, move the model to the origin but we can look to change this if needed
        modelInstance.transform.position = Vector3.zero;

        // Disable ALL child meshes of the avatar, except for the base avatar mesh of the segmentation avatar named "base_avatar_for_segmentationMesh"
        var meshRenderers = modelInstance.GetComponentsInChildren<MeshRenderer>(true);
        foreach (var meshRenderer in meshRenderers)
        {
            if (meshRenderer.gameObject.name != SEGMENTATION_AVATAR_MESH_NAME)
            {
                meshRenderer.gameObject.SetActive(false);
            }
        }
        var skinnedMeshRenderers = modelInstance.GetComponentsInChildren<SkinnedMeshRenderer>(true);
        foreach (var skinnedMeshRenderer in skinnedMeshRenderers)
        {
            if (skinnedMeshRenderer.gameObject.name != SEGMENTATION_AVATAR_MESH_NAME)
            {
                skinnedMeshRenderer.gameObject.SetActive(false);
            }
        }

        // Set the base avatar mesh's material to the Invisible Mask, which allows us to perform segmentation (NOT THE CLOTHES)
        // The goal of this material is to make the base avatar invisible in the scene, but still obscure the clothed avatar where it makes sense.
        // For example, the inside of a hat should be obscured by the avatar's head, the collar of a shirt should be obscured by the avatar's neck, etc.
        // NOTE: We do this for the base avatar for segmentation (which has skin under shirt and pants missing) and not the base avatar of the clothed_avatar itself to avoid clipping.
        print("[Keegan Debug]: modelInstance.name = " + modelInstance.name);
        if (modelInstance.name == SEGMENTATION_AVATAR_TOP_LEVEL_NAME) {
            Material invisibleMaskMaterial = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/InvisibleMask.mat");
            if (invisibleMaskMaterial != null)
            {
                Transform meshTransform = modelInstance.transform.Find("clothed_avatarMesh");
                if (meshTransform != null)
                {
                    var meshRenderer = meshTransform.GetComponent<MeshRenderer>();
                    if (meshRenderer != null)
                    {
                        meshRenderer.sharedMaterial = invisibleMaskMaterial;
                        Debug.Log("[AvatarSpawner] Set Invisible Mask material on MeshRenderer of 'clothed_avatarMesh'.");
                    }
                    var skinnedMeshRenderer = meshTransform.GetComponent<SkinnedMeshRenderer>();
                    if (skinnedMeshRenderer != null)
                    {
                        skinnedMeshRenderer.sharedMaterial = invisibleMaskMaterial;
                        Debug.Log("[AvatarSpawner] Set Invisible Mask material on SkinnedMeshRenderer of 'clothed_avatarMesh'.");
                    }
                }
                else
                {
                    Debug.LogWarning("[AvatarSpawner] Child named 'clothed_avatarMesh' not found in model instance.");
                }
            }
            else
            {
                Debug.LogWarning("[AvatarSpawner] Invisible Mask material not found at Assets/Materials/InvisibleMask.mat");
            }
        }

        Debug.Log($"[AvatarSpawner] Spawned model instance: {modelInstance.name}");
        return modelInstance;
    }

    // Set instance's Animator -> Controller
    private static Animator SetupAnimatorComponent(GameObject avatarInstance, string assetPath)
    {
        // Create an Animator component for the avatar instance in the scene if it doesn't already exist.
        Animator animator = avatarInstance.GetComponent<Animator>();
        if (animator == null){
            animator = avatarInstance.AddComponent<Animator>();
        }
        
        // Retrieve the animation controller for this avatar
        // This should have be created by the FbxImportHandler.cs script.
        string assetDirectory = Path.GetDirectoryName(assetPath);
        string modelName = Path.GetFileNameWithoutExtension(assetPath);
        string controllerName = $"{modelName}.controller";
        string controllerPath = $"{assetDirectory}/{controllerName}".Replace("\\", "/");

        // Load the created animation controller and set the avatar instance's animator to use it.
        RuntimeAnimatorController controller = AssetDatabase.LoadAssetAtPath<RuntimeAnimatorController>(controllerPath);
        if (controller != null)
        {
            Debug.Log($"[AvatarSpawner] Setting animator runtime controller to: {controller.name}");
            animator.runtimeAnimatorController = controller;
        } else {
            Debug.LogError($"[AvatarSpawner] Animation controller not found at: {controllerPath}. Check the FbxImportHandler.cs script to ensure the controller was created.");
        }

        return animator;
    }

    // Set instance's Avatar Controller (Script)
    private static void AddAvatarControllerScriptToSpawnedAvatar(GameObject avatarInstance, Animator avatarAnimator)
    {
        // Create "Script" component for the avatar instance
        AvatarController avatarScript = avatarInstance.AddComponent<AvatarController>();

        // Set script parameters
        avatarScript.animator = avatarAnimator;
        avatarScript.ClothedBaseAvatar = avatarInstance;
        avatarScript.enableInverseKinematics = false;
        
        GameObject bodyManager = GameObject.Find("BodyManager");
        if (bodyManager != null){
            avatarScript.BodySourceManager = bodyManager;
        } else {
            Debug.LogError($"[AvatarSpawner] BodyManager not found. Please add a BodyManager object to the scene.");
        }

        Debug.Log($"[AvatarSpawner] Added AvatarController script to: {avatarInstance.name}");
    }
#endif
}
