using UnityEngine;
using UnityEditor;
using System.IO;

/*
This script is responsible for spawning the clothed avatar model in the scene, after it has been imported and
processed by the FbxImportHandler.cs script.

It runs after the scene loads but before Start() is called on any object.
We need to run it after the scene loads because we need to find the BodyManager object in the scene.
*/
public class AvatarSpawner : MonoBehaviour
{
    // The directory that holds the clothed avatar models generated by MakeHuman and postprocessed by the FbxImportHandler.cs script.
    const string CLOTHED_AVATAR_DIRECTORY = "Assets/Base Models";

    // The script that controls the clothed avatar model.
    // We need to add this as a component to the clothed avatar model after it is spawned.
    const string AVATAR_CONTROLLER_SCRIPT = "AvatarController";

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] // Run after scene loads, but before Start() is called on any object.
    static void OnAfterSceneLoad()
    {
#if UNITY_EDITOR
        // Find all FBX files in the clothed avatar directory.
        Debug.Log($"[AvatarSpawner] Looking for clothed avatar models in {CLOTHED_AVATAR_DIRECTORY}");
        string [] modelGuids = AssetDatabase.FindAssets("t:Model", new [] {CLOTHED_AVATAR_DIRECTORY});

        foreach (string modelGuid in modelGuids)
        {
            string assetPath = AssetDatabase.GUIDToAssetPath(modelGuid);

            // Skip if not a .fbx file
            if (!assetPath.EndsWith(".fbx")) continue;

            Debug.Log($"[AvatarSpawner] Found clothed avatar model: {assetPath}");

            // Load the model prefab
            GameObject modelPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);

            // Skip this object if it's already in the scene.
            if (GameObject.Find(modelPrefab.name) != null) continue;

            // Spawn the model in the scene and get the Animator component
            GameObject avatarInstance = SpawnModelInScene(modelPrefab);

            // Perform setup of the model now that it is in the scene
            Animator avatarAnimator = SetupAnimatorComponent(avatarInstance, assetPath);
            AddAvatarControllerScriptToSpawnedAvatar(avatarInstance, avatarAnimator);
        }
    }

    // Spawns a model in the scene and returns the game object.
    private static GameObject SpawnModelInScene(GameObject modelPrefab)
    {
        GameObject modelInstance = Object.Instantiate(modelPrefab);
        modelInstance.name = modelPrefab.name; // removes "(Clone) from the instance's name

        // For now, move the model to the origin but we can look to change this if needed
        modelInstance.transform.position = Vector3.zero;

        // Disable all child meshes
        var meshRenderers = modelInstance.GetComponentsInChildren<MeshRenderer>(true);
        foreach (var meshRenderer in meshRenderers)
        {
            meshRenderer.gameObject.SetActive(false);
        }
        var skinnedMeshRenderers = modelInstance.GetComponentsInChildren<SkinnedMeshRenderer>(true);
        foreach (var skinnedMeshRenderer in skinnedMeshRenderers)
        {
            skinnedMeshRenderer.gameObject.SetActive(false);
        }

        Debug.Log($"[AvatarSpawner] Spawned model instance: {modelInstance.name} (all child meshes set inactive)");
        return modelInstance;
    }

    // Set instance's Animator -> Controller
    private static Animator SetupAnimatorComponent(GameObject avatarInstance, string assetPath)
    {
        // Create an Animator component for the avatar instance in the scene if it doesn't already exist.
        Animator animator = avatarInstance.GetComponent<Animator>();
        if (animator == null){
            animator = avatarInstance.AddComponent<Animator>();
        }
        
        // Retrieve the animation controller for this avatar
        // This should have be created by the FbxImportHandler.cs script.
        string assetDirectory = Path.GetDirectoryName(assetPath);
        string modelName = Path.GetFileNameWithoutExtension(assetPath);
        string controllerName = $"{modelName}.controller";
        string controllerPath = $"{assetDirectory}/{controllerName}".Replace("\\", "/");

        // Load the created animation controller and set the avatar instance's animator to use it.
        RuntimeAnimatorController controller = AssetDatabase.LoadAssetAtPath<RuntimeAnimatorController>(controllerPath);
        if (controller != null)
        {
            Debug.Log($"[AvatarSpawner] Setting animator runtime controller to: {controller.name}");
            animator.runtimeAnimatorController = controller;
        } else {
            Debug.LogError($"[AvatarSpawner] Animation controller not found at: {controllerPath}. Check the FbxImportHandler.cs script to ensure the controller was created.");
        }

        return animator;
    }

    // Set instance's Avatar Controller (Script)
    private static void AddAvatarControllerScriptToSpawnedAvatar(GameObject avatarInstance, Animator avatarAnimator)
    {
        // Create "Script" component for the avatar instance
        AvatarController avatarScript = avatarInstance.AddComponent<AvatarController>();

        // Set script parameters
        avatarScript.animator = avatarAnimator;
        avatarScript.ClothedBaseAvatar = avatarInstance;
        avatarScript.enableInverseKinematics = false;
        
        GameObject bodyManager = GameObject.Find("BodyManager");
        if (bodyManager != null){
            avatarScript.BodySourceManager = bodyManager;
        } else {
            Debug.LogError($"[AvatarSpawner] BodyManager not found. Please add a BodyManager object to the scene.");
        }

        Debug.Log($"[AvatarSpawner] Added AvatarController script to: {avatarInstance.name}");
    }
#endif
}
