using UnityEngine;
using UnityEditor;
using System.IO;

/*
This script processes new FBX files in the Assets/Base Models folder, performing the following steps when the new clothed avatar model is imported:
1. Set rig to Humanoid.
2. Set Materials (textures) accordingly.
3. Set Models > Normals to "Calculate". This is required to fix an issue where clothing textures appeared white and splotchy.
The rest of the Model setup steps involving the Scene itself are performed by the AutoAvatarSpawner.cs script.
*/
public class FbxImportHandler : AssetPostprocessor
{
    // The directory that will holds the clothed avatar models generated by MakeHuman.
    const string CLOTHED_AVATAR_DIRECTORY = "Assets/Base Models";

    // The model should only be processed if it is in the clothed avatar directory and is an fbx file.
    private bool ShouldProcess()
    {
        return assetPath.Contains(CLOTHED_AVATAR_DIRECTORY) && assetPath.EndsWith(".fbx");
    }

    // Cast to ModelImporter to access model-specific properties
    ModelImporter ModelImporter => (ModelImporter)assetImporter;

    void OnPreprocessModel()
    {
        if (!ShouldProcess()) return;

        // If the model is already humanoid, assume we've already processed it and return early.
        if (ModelImporter.animationType == ModelImporterAnimationType.Human) return;

        Debug.Log($"[FbxImportHandler] Processing new MakeHuman clothed avatar model: {assetPath}");
        SetRigToHumanoid();
        SetModelNormalsToCalculate();
        SetMaterials();
        SetMiscSettings();
        Debug.Log($"[FbxImportHandler] Processing complete for new MakeHuman clothed avatar model: {assetPath}");
    }

    // Sets the rig to Humanoid. Required for our model to be controlled with the AvatarController.cs script.
    void SetRigToHumanoid()
    {
        ModelImporter.animationType = ModelImporterAnimationType.Human;
    }

    // Eliminate white splotches on the model's clothing textures.
    void SetModelNormalsToCalculate()
    {
        ModelImporter.importNormals = ModelImporterNormals.Calculate;
        ModelImporter.normalCalculationMode = ModelImporterNormalCalculationMode.AngleWeighted;
        ModelImporter.normalSmoothingAngle = 60f;
    }

    // Set the materials for the model.
    // Mimics clicking "Materials > Extract Materials" and selecting the directory containing the model's textures in the GUI.
    void SetMaterials()
    {
        ModelImporter.materialImportMode = ModelImporterMaterialImportMode.ImportViaMaterialDescription;
        ModelImporter.materialLocation = ModelImporterMaterialLocation.InPrefab;
        ModelImporter.materialName = ModelImporterMaterialName.BasedOnMaterialName;
    }

    // Set misc settings for the model.
    void SetMiscSettings() {
        ModelImporter.importBlendShapes = true;
        ModelImporter.importVisibility = true;
        ModelImporter.importCameras = false;
        ModelImporter.importLights = false;
        ModelImporter.globalScale = 1.0f;
        ModelImporter.useFileScale = true;
    }
}
